colors: true

pre-commit:
  commands:
    biome:
      glob: "*.{ts,tsx,js,jsx,md,mdx,json,yaml,html,css,scss,sass,less}"
      run: "pnpm lint:staged --write"
      stage_fixed: true

commit-msg:
  commands:
    commitlint:
      run: npx --no -- commitlint --edit $1
