packages:
  - "packages/*"
  - "configs/*"

minimumReleaseAge: 0

allowBuilds:
  "@swc/core": false
  better-sqlite3: true
  core-js-pure: false
  dtrace-provider: false
  esbuild: false
  lefthook: true
  nx: true
  protobufjs: false
  re2: true
