module.exports = {
  singleQuote: true,
  trailingComma: 'all',
  semi: true,
  printWidth: 100,
  arrowParens: 'avoid',
  jsxSingleQuote: false,
  tabWidth: 2,
  endOfLine: 'lf',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxBracketSameLine: false,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  useTabs: false,
};
