module.exports = {
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  jsxSingleQuote: true,
  printWidth: 100,
  semi: true,
  trailingComma: 'all',
  endOfLine: 'lf',
  arrowParens: 'avoid',
  bracketSpacing: true,
  quoteProps: 'as-needed',
  // htmlWhitespaceSensitivity: 'css',
  // insertPragma: false,
  // jsxBracketSameLine: false,
  // proseWrap: 'always',
  // useTabs: false,
};
