module.exports = {
  env: {
    browser: true,
    es2021: true,
    es6: true,
    node: true,
  },
  extends: ['eslint:recommended', './partials/imports'],
  parserOptions: {
    ecmaVersion: 'latest',
  },
  rules: {
    'array-bracket-newline': ['error', { minItems: 2, multiline: true }],
    'array-bracket-spacing': ['error', 'always'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'arrow-spacing': ['error', { after: true, before: true }],
    'block-spacing': ['error', 'never'],
    'brace-style': ['error', 'stroustrup'],
    'capitalized-comments': ['error', 'always'],
    curly: ['error', 'multi', 'consistent'],
    'default-case': ['error', { commentPattern: '^skip\\sdefault' }],
    'default-case-last': 'error',
    'default-param-last': ['error'],
    'function-paren-newline': ['error', { minItems: 3 }],
    'implicit-arrow-linebreak': ['error', 'beside'],
    'key-spacing': [
      'error',
      {
        afterColon: true,
        align: 'value',
        beforeColon: false,
      },
    ],
    'keyword-spacing': ['error', { after: true, before: true }],
    'line-comment-position': ['error', { position: 'above' }],
    'lines-around-comment': [
      'error',
      { allowClassStart: true, beforeBlockComment: true, beforeLineComment: true },
    ],
    'lines-between-class-members': ['error', 'always'],
    'max-nested-callbacks': ['error', 3],
    'multiline-comment-style': ['error', 'starred-block'],
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-const-assign': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty': 'error',
    'no-empty-static-block': 'error',
    'no-extra-boolean-cast': ['error', { enforceForLogicalOperands: true }],
    'no-inline-comments': 'error',
    'no-invalid-regexp': 'error',
    'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
    'no-negated-condition': 'warn',
    'no-redeclare': 'error',
    'no-throw-literal': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      },
    ],
    'no-use-before-define': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-warning-comments': [
      'warn',
      {
        location: 'anywhere',
        terms: ['todo', 'fixme', 'any other term'],
      },
    ],
    'object-curly-newline': [
      'error',
      {
        consistent: true,
        minProperties: 3,
        multiline: true,
      },
    ],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': 'error',
    'object-shorthand': ['error', 'always', { avoidQuotes: true }],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': ['error', { array: false, object: true }],
    'prefer-object-has-own': 'error',
    'prefer-rest-params': 'warn',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'quote-props': ['error', 'as-needed'],
    'rest-spread-spacing': ['error', 'never'],
    'space-in-parens': ['error', 'always'],
    'spaced-comment': ['error', 'always'],
    'template-curly-spacing': ['error', 'always'],
  },
};
