module.exports = {
  env: {
    browser: true,
    es2021: true,
    es6: true,
    node: true,
  },
  extends: ['eslint:recommended', './partials/imports'],
  parserOptions: {
    ecmaVersion: 'latest',
  },
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    'consistent-return': 'error',
    curly: ['error', 'multi', 'consistent'],
    'default-case': ['error', { commentPattern: '^skip\\sdefault' }],
    'default-case-last': 'error',
    'default-param-last': ['error'],
    'max-nested-callbacks': ['error', 3],
    'multiline-comment-style': ['error', 'starred-block'],
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-const-assign': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty': 'error',
    'no-empty-static-block': 'error',
    'no-extra-boolean-cast': ['error', { enforceForLogicalOperands: true }],
    'no-inline-comments': 'error',
    'no-negated-condition': 'warn',
    'no-redeclare': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-use-before-define': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-warning-comments': [
      'warn',
      {
        location: 'anywhere',
        terms: ['todo', 'fixme', 'any other term'],
      },
    ],
    'object-shorthand': ['error', 'consistent-as-needed'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-object-has-own': 'error',
    'prefer-rest-params': 'warn',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'quote-props': ['error', 'as-needed'],
    'require-await': 'error',
    'spaced-comment': ['error', 'always'],
  },
};
