name: "Setup Node and PNPM"

description: "Installs Node and PNPM dependencies"

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: pnpm/action-setup@v5
      name: 📥 Install PNPM

    # - name: 📂 Get PNPM store directory
    #   shell: bash
    #   run: |
    #     echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    # - uses: actions/cache@v4
    #   name: 💾 Setup PNPM cache
    #   with:
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     path: ${{ env.STORE_PATH }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm-store-

    - name: 📲 Install project dependencies
      shell: bash
      run: CI=true pnpm install --shamefully-hoist
