name: "Setup Node and PNPM"

description: "Sets up Node.js, PNPM, and installs dependencies"

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: pnpm/action-setup@v5
      name: 📥 Install PNPM

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: 📲 Install project dependencies
      shell: bash
      run: CI=true pnpm install --frozen-lockfile
