#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#exec < /dev/tty && node_modules/.bin/cz --hook || true

if [[ "$2" != *"publish"* ]];then
    exec < /dev/tty && node_modules/.bin/cz --hook "$1" "$2" "$3" || true
fi